import torch
import torchaudio
import soundfile as sf
from pathlib import Path
import sys
import warnings
import os

warnings.filterwarnings("ignore", category=UserWarning, module="torch")
# ── Point this to your local F5-TTS clone ──────────────────────────────────
F5_ROOT = Path("./F5-TTS")  
sys.path.insert(0, str(F5_ROOT / "src"))

from f5_tts.model import DiT
from f5_tts.infer.utils_infer import (
    load_vocoder,
    load_model,
    preprocess_ref_audio_text,
    infer_process,
)


# ── Config ──────────────────────────────────────────────────────────────────
DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"

# Path to your checkpoint — swap this for your fine-tuned .pt/.safetensors
CKPT_PATH = F5_ROOT / "ckpts" / "F5TTS_v1_Base" / "model_1250000.safetensors"

num_speakers = 1 #20

REF_AUDIO_FOLDER  = "VCTK-Corpus-0.92/wav48_silence_trimmed"   # <-- your reference voice clip
REF_TEXT_FOLDER   = "VCTK-Corpus-0.92/txt"   # <-- your reference text file
OUTPUT_WAV_FOLDER  = "./" #"./Output/F5TTS"   # <-- where to save generated audio
os.makedirs(OUTPUT_WAV_FOLDER, exist_ok=True)


# ── Model architecture (must match F5-TTS Base config), V1 architecture ──────────────────────
model_cfg = dict(
    dim=1024,
    depth=22,
    heads=16,
    ff_mult=2,
    text_dim=512,
    text_mask_padding=True,   # ← new in v1
    conv_layers=4,
)

# ── Tokenizer (vocab file ships with the repo) ───────────────────────────────
vocab_file = F5_ROOT / "ckpts" / "F5TTS_v1_Base" / "vocab.txt"


# ── Load everything ──────────────────────────────────────────────────────────
print("Loading vocoder (Vocos)...")
vocoder = load_vocoder(vocoder_name="vocos", is_local=False, device=DEVICE)

print("Loading F5-TTS model from local checkpoint...")
model = load_model(
    model_cls     = DiT,
    model_cfg     = model_cfg,
    ckpt_path     = str(CKPT_PATH),
    mel_spec_type = "vocos",
    vocab_file    = vocab_file,       
    device        = DEVICE,
)
model.eval()

# ── Preprocess reference audio + text ────────────────────────────────────────
initial_speaker_id = 225
for i in range(num_speakers):
    print(f"Preprocessing reference audio {i}...")
    REF_AUDIO_PATH = f"{REF_AUDIO_FOLDER}/p{str(initial_speaker_id + i)}/p{str(initial_speaker_id + i)}_003_mic1.flac"
    REF_TEXT_PATH = f"{REF_TEXT_FOLDER}/p{str(initial_speaker_id + i)}/p{str(initial_speaker_id + i)}_003.txt"
    if not os.path.exists(REF_AUDIO_PATH) or not os.path.exists(REF_TEXT_PATH):
        print(f"Reference audio or text for speaker {initial_speaker_id + i} not found. Skipping...")
        continue
    with open(REF_TEXT_PATH, "r") as f:
        REF_TEXT = f.read()
    TARGET_TEXT = "Hello I am the voice generated by Poorvai Chandrasen and this is a spoofed speech using Star gan v 2."#f"Hello, I am the audio generated by Ms. Poorvai Chandrasen. I am speaker p{str(initial_speaker_id + i)} created using audio generation from F5TTS. This is example {str(9 + i)}."     # <-- what to say
    OUTPUT_WAV = "Output_content.wav" #f"{OUTPUT_WAV_FOLDER}/output_p{str(initial_speaker_id + i)}.wav"
    ref_audio_proc, ref_text_proc = preprocess_ref_audio_text(
        REF_AUDIO_PATH,
        REF_TEXT,
    )

# ── Run inference ─────────────────────────────────────────────────────────────
    print("Running inference...")
    with torch.inference_mode():
        audio_out, sample_rate, _ = infer_process(
            ref_audio    = ref_audio_proc,
            ref_text     = ref_text_proc,
            gen_text     = TARGET_TEXT,
            model_obj    = model,
            vocoder      = vocoder,
            mel_spec_type= "vocos",
            device       = DEVICE,
        )

    # ── Save output ───────────────────────────────────────────────────────────────
    sf.write(OUTPUT_WAV, audio_out.squeeze(), sample_rate)
    print(f"Saved output no. {i} → {OUTPUT_WAV}")