# -*- coding: utf-8 -*-
"""using lib audio processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110x61gGUwgyNdwVLVG-CnMD-Sk66sITH
"""

import librosa
import numpy as np
import matplotlib.pyplot as plt

# list of your audio files
audio_files = [
    "/content/fake-0.mp3",
    "/content/fake-1.mp3",
    "/content/fake-2.mp3",
    "/content/real.mp3"
]

plt.figure(figsize=(12,10))

for i, file in enumerate(audio_files):

    # Load audio
    y, sr = librosa.load(file)

    # -------------------------
    # Pitch (F0)
    # -------------------------
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)

    pitch_values = []
    for t in range(pitches.shape[1]):
        index = magnitudes[:, t].argmax()
        pitch = pitches[index, t]
        if pitch > 0:
            pitch_values.append(pitch)

    # -------------------------
    # Energy
    # -------------------------
    energy = np.sum(y**2) / len(y)

    # -------------------------
    # Speaking Speed
    # -------------------------
    duration = librosa.get_duration(y=y, sr=sr)

    # Onset detection for approximate speaking rate
    onset_frames = librosa.onset.onset_detect(y=y, sr=sr)
    speaking_rate = len(onset_frames) / duration

    print("File:", file)
    print("Average Pitch:", np.mean(pitch_values))
    print("Energy:", energy)
    print("Duration:", duration)
    print("Speaking rate:", speaking_rate)
    print("---------------------------")

    # -------------------------
    # Pitch Contour Plot
    # -------------------------
    plt.subplot(4,1,i+1)
    plt.plot(pitch_values)
    plt.title(f"Pitch contour - {file}")

plt.tight_layout()
plt.show()

import librosa.display

mel = librosa.feature.melspectrogram(y=y, sr=sr)
mel_db = librosa.power_to_db(mel, ref=np.max)

plt.figure(figsize=(10,4))
librosa.display.specshow(mel_db, sr=sr, x_axis='time', y_axis='mel')
plt.title("Mel Spectrogram")
plt.colorbar(format='%+2.0f dB')
plt.show()

pitch_range = np.max(pitch_values) - np.min(pitch_values)
print("Pitch Range:", pitch_range) #speech anlysis

import scipy.signal

smooth_pitch = scipy.signal.medfilt(pitch_values, kernel_size=5)

plt.plot(smooth_pitch)
plt.title("Smoothed Pitch Contour")
plt.show()

print("Min pitch:", np.min(pitch_values))
print("Max pitch:", np.max(pitch_values))
print("Pitch variance:", np.var(pitch_values))

intervals = librosa.effects.split(y, top_db=30)
print("Number of speech segments:", len(intervals)) #silence anlysis

energy = librosa.feature.rms(y=y)

plt.plot(energy[0])
plt.title("Energy Contour")
plt.show()  #energy over time

centroid = librosa.feature.spectral_centroid(y=y, sr=sr)
print("Avg spectral centroid:", np.mean(centroid))

tempo, beats = librosa.beat.beat_track(y=y, sr=sr)

print("Estimated speech tempo:", tempo)

for file in audio_files:
    y, sr = librosa.load(file)
    pitches, magnitudes = librosa.piptrack(y=y, sr=sr)

    pitch_values = []
    for t in range(pitches.shape[1]):
        index = magnitudes[:, t].argmax()
        pitch = pitches[index, t]
        if pitch > 0:
            pitch_values.append(pitch)

    plt.plot(pitch_values,label=file)

plt.legend()
plt.title("Pitch Comparison")
plt.show()

bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)
print("Bandwidth:", np.mean(bandwidth)) #high bandwidhth means expressive speech

from librosa.sequence import dtw

D, wp = dtw(mfcc1, mfcc2)
print("DTW distance:", D[-1,-1])